const CiudadesLista=[
  { "id": "Quito", "descripcion": "Quito" },
  { "id": "Guayaquil", "descripcion": "Guayaquil" },
  { "id": "Cuenca", "descripcion": "Cuenca" },
  { "id": "Santo Domingo", "descripcion": "Santo Domingo" },
  { "id": "Machala", "descripcion": "Machala" },
  { "id": "Durán", "descripcion": "Durán" },
  { "id": "Manta", "descripcion": "Manta" },
  { "id": "Portoviejo", "descripcion": "Portoviejo" },
  { "id": "Ambato", "descripcion": "Ambato" },
  { "id": "Riobamba", "descripcion": "Riobamba" },
  { "id": "Loja", "descripcion": "Loja" },
  { "id": "Esmeraldas", "descripcion": "Esmeraldas" },
  { "id": "Quevedo", "descripcion": "Quevedo" },
  { "id": "Milagro", "descripcion": "Milagro" },
  { "id": "Ibarra", "descripcion": "Ibarra" },
  { "id": "Latacunga", "descripcion": "Latacunga" },
  { "id": "Babahoyo", "descripcion": "Babahoyo" },
  { "id": "Tulcán", "descripcion": "Tulcán" },
  { "id": "Azogues", "descripcion": "Azogues" },
  { "id": "Nueva Loja", "descripcion": "Nueva Loja" },
  { "id": "Tena", "descripcion": "Tena" },
  { "id": "Puyo", "descripcion": "Puyo" },
  { "id": "Macas", "descripcion": "Macas" },
  { "id": "Zamora", "descripcion": "Zamora" },
  { "id": "Santa Elena", "descripcion": "Santa Elena" },
  { "id": "Salinas", "descripcion": "Salinas" },
  { "id": "La Libertad", "descripcion": "La Libertad" },
  { "id": "Chone", "descripcion": "Chone" },
  { "id": "Bahía de Caráquez", "descripcion": "Bahía de Caráquez" },
  { "id": "Jipijapa", "descripcion": "Jipijapa" },
  { "id": "Montecristi", "descripcion": "Montecristi" },
  { "id": "Pasaje", "descripcion": "Pasaje" },
  { "id": "Santa Rosa", "descripcion": "Santa Rosa" },
  { "id": "Huaquillas", "descripcion": "Huaquillas" },
  { "id": "El Coca", "descripcion": "El Coca" },
  { "id": "Guaranda", "descripcion": "Guaranda" },
  { "id": "San Gabriel", "descripcion": "San Gabriel" },
  { "id": "Pelileo", "descripcion": "Pelileo" },
  { "id": "Baños", "descripcion": "Baños" },
  { "id": "Cayambe", "descripcion": "Cayambe" },
  { "id": "Otavalo", "descripcion": "Otavalo" },
  { "id": "Sangolquí", "descripcion": "Sangolquí" },
  { "id": "Machachi", "descripcion": "Machachi" },
  { "id": "Pedro Vicente Maldonado", "descripcion": "Pedro Vicente Maldonado" },
  { "id": "San Miguel de los Bancos", "descripcion": "San Miguel de los Bancos" },
  { "id": "Puerto Ayora", "descripcion": "Puerto Ayora" }
]

export default CiudadesLista;