export const direcionTalleres = {
    "ATACAMES": "AV. PRINCIPAL S/N FRENTE AL HOSPITAL JUAN GUSTAVO DIAG A GASOLINERA TERPEL",
    "EL CARMEN": "AV. CHONE Y 4 DE DICIEMBRE FRENTE A LAS RUTAS CARMENSES",
    "CONCORDIA": "CALLE GUAYAS S/N SIMON PLATA TORRES FRENTE A ORVE HOGAR",
    "MILAGRO 2": "JUAN MONTALVO Y VARGAS TORRES ESQUINA",
    "MILAGRO": "JUAN MONTALVO Y VARGAS TORRES ESQUINA",
    "NARANJAL": "CALLE GUAYAQUIL ENTRE 24 DE MAYO Y CUENCA FRENTE PUNTO DE LA SUERTE LOTERIA NACIONAL",
    "PORTOVIEJO": "AV. UNIVERSITARIA S/N RAMOS DUARTE",
    "QUEVEDO": "CALLE BOLIVAR Y DECIMA BOLIVAR ESQ.",
    "VIA DAULE": "KM 11.5 VIA A DAULE PLAZA SAN JORGE LOCAL 13-14 JUNTO AL CORAL HIPERMERCADOS",
    "QUININDE": "AV SIMON PLATA TORRES Y GUSTAVO BECERRA FRENTE AL BANCO INTERNACIONAL",
    "STO DOMINGO": "AV. ESMERALDAS Y AV. SANTA ROSA ESQUINA FRENTE A LA GASOLINERA PRIMAX",
    "SANTO DOMINGO": "AV. ESMERALDAS Y AV. SANTA ROSA ESQUINA FRENTE A LA GASOLINERA PRIMAX",
    "MANTA": "CALLE 13 ENTRE AVS 17 Y 18 al lado ASADERO LA ESQUINA DE ALES",
    "CUENCA": "AV. JOSE PERALTA Y ALFONSO CORDERO JUNTO A ORO MAR",
    "IBARRA": "AV. MARIANO ACOSTA 23-07 JUNTO AL SUPERMAXI",
    "QUITO NORTE": "10 DE AGOSTO Y DE LAS RETAMAS E1-60",
    "TENA": "AV. 15 DE NOVIEMBRE Y 12 DE FEBRERO"
  };